<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:connectorconfiguration="http://www.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_22OOIGDDEfGY0qGQ08NUOw" name="Visualiser le quota des agents" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_22OOIWDDEfGY0qGQ08NUOw" name="Visualiser les quotas des agents">
      <elements xmi:type="process:Lane" xmi:id="_22OOImDDEfGY0qGQ08NUOw" name="Manager" actor="_ngM9kGYtEfGz1Ym7HCRQpA">
        <elements xmi:type="process:StartEvent" xmi:id="_22OOI2DDEfGY0qGQ08NUOw" name="Démarrer1" outgoing="_VNNqMGY0EfG2XcJ39Idavg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_22OOJGDDEfGY0qGQ08NUOw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_22OOJWDDEfGY0qGQ08NUOw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_22OOJmDDEfGY0qGQ08NUOw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_22OOJ2DDEfGY0qGQ08NUOw" name="Visualiser les quotas" outgoing="_22OOTGDDEfGY0qGQ08NUOw" incoming="_VNNqMGY0EfG2XcJ39Idavg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_22OOKGDDEfGY0qGQ08NUOw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_22OOKWDDEfGY0qGQ08NUOw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_22OOKmDDEfGY0qGQ08NUOw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_22OOK2DDEfGY0qGQ08NUOw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_22OOLGDDEfGY0qGQ08NUOw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_22OOLWDDEfGY0qGQ08NUOw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_22OOLmDDEfGY0qGQ08NUOw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_22OOL2DDEfGY0qGQ08NUOw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_22OOMGDDEfGY0qGQ08NUOw">
            <targetForm xmi:type="expression:Expression" xmi:id="_Xs8-4GY7EfGz1Ym7HCRQpA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <filters xmi:type="process:ActorFilter" xmi:id="_YtKi4GY0EfG2XcJ39Idavg" name="Initiateur" definitionId="bonita-actorfilter-initiator" definitionVersion="1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_YtKi4WY0EfG2XcJ39Idavg" definitionId="bonita-actorfilter-initiator" version="1.0">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_YtKi4mY0EfG2XcJ39Idavg" key="autoAssign">
                <expression xmi:type="expression:Expression" xmi:id="_YtLJ8GY0EfG2XcJ39Idavg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
            </configuration>
          </filters>
          <contract xmi:type="process:Contract" xmi:id="_22OOMmDDEfGY0qGQ08NUOw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_22OOM2DDEfGY0qGQ08NUOw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_22OONGDDEfGY0qGQ08NUOw" name="Fin1" incoming="_22OOTGDDEfGY0qGQ08NUOw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_22OONWDDEfGY0qGQ08NUOw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_22OONmDDEfGY0qGQ08NUOw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_22OON2DDEfGY0qGQ08NUOw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_lfWb8GY0EfG2XcJ39Idavg" name="quotas" multiple="true" dataType="_22OObWDDEfGY0qGQ08NUOw" className="com.company.model.QuotaCarbone">
        <defaultValue xmi:type="expression:Expression" xmi:id="_lfWb8WY0EfG2XcJ39Idavg" name="init_quotas()" content="def quotas = quotaCarboneDAO.find(0, 100)&#xD;&#xA;&#xD;&#xA;return quotas" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
          <referencedElements xmi:type="expression:Expression" xmi:id="_lfWb8mY0EfG2XcJ39Idavg" name="quotaCarboneDAO" content="quotaCarboneDAO" type="TYPE_BUSINESS_OBJECT_DAO" returnType="com.company.model.QuotaCarboneDAO" returnTypeFixed="true"/>
        </defaultValue>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_22OORWDDEfGY0qGQ08NUOw">
        <targetForm xmi:type="expression:Expression" xmi:id="_OVCbAGZAEfGz1Ym7HCRQpA" name="FormVIsualiserLesQuotas" content="08010cbf-77d7-4a26-95b3-ea2120684348" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_22OOR2DDEfGY0qGQ08NUOw">
        <targetForm xmi:type="expression:Expression" xmi:id="_22OOSGDDEfGY0qGQ08NUOw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_22OOTGDDEfGY0qGQ08NUOw" target="_22OONGDDEfGY0qGQ08NUOw" source="_22OOJ2DDEfGY0qGQ08NUOw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_22OOTWDDEfGY0qGQ08NUOw"/>
        <condition xmi:type="expression:Expression" xmi:id="_22OOTmDDEfGY0qGQ08NUOw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VNNqMGY0EfG2XcJ39Idavg" target="_22OOJ2DDEfGY0qGQ08NUOw" source="_22OOI2DDEfGY0qGQ08NUOw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VNNqMWY0EfG2XcJ39Idavg"/>
        <condition xmi:type="expression:Expression" xmi:id="_VNNqMmY0EfG2XcJ39Idavg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_22OOUmDDEfGY0qGQ08NUOw" documentation="Ceci est un exemple d'acteur associé à tous les utilisateurs d'ACME" name="Employee actor"/>
      <actors xmi:type="process:Actor" xmi:id="_22OOU2DDEfGY0qGQ08NUOw" name="Agent"/>
      <actors xmi:type="process:Actor" xmi:id="_ngM9kGYtEfGz1Ym7HCRQpA" name="Manager" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_22OOVWDDEfGY0qGQ08NUOw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_22OOVmDDEfGY0qGQ08NUOw">
        <name xmi:type="expression:Expression" xmi:id="_22OOV2DDEfGY0qGQ08NUOw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_22OOWGDDEfGY0qGQ08NUOw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_22OOWWDDEfGY0qGQ08NUOw">
        <name xmi:type="expression:Expression" xmi:id="_22OOWmDDEfGY0qGQ08NUOw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_22OOW2DDEfGY0qGQ08NUOw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_22OOXGDDEfGY0qGQ08NUOw">
        <name xmi:type="expression:Expression" xmi:id="_22OOXWDDEfGY0qGQ08NUOw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_22OOXmDDEfGY0qGQ08NUOw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_22OOX2DDEfGY0qGQ08NUOw">
        <name xmi:type="expression:Expression" xmi:id="_22OOYGDDEfGY0qGQ08NUOw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_22OOYWDDEfGY0qGQ08NUOw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_22OOYmDDEfGY0qGQ08NUOw">
        <name xmi:type="expression:Expression" xmi:id="_22OOY2DDEfGY0qGQ08NUOw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_22OOZGDDEfGY0qGQ08NUOw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_22OOZWDDEfGY0qGQ08NUOw" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_22OOZmDDEfGY0qGQ08NUOw" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_22OOZ2DDEfGY0qGQ08NUOw" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_22OOaGDDEfGY0qGQ08NUOw" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_22OOaWDDEfGY0qGQ08NUOw" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_22OOamDDEfGY0qGQ08NUOw" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_22OOa2DDEfGY0qGQ08NUOw" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_22OObGDDEfGY0qGQ08NUOw" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_22OObWDDEfGY0qGQ08NUOw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_22OObmDDEfGY0qGQ08NUOw" type="Process" element="_22OOIGDDEfGY0qGQ08NUOw" name="MonDiagramme" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_22O1MGDDEfGY0qGQ08NUOw" type="2007" element="_22OOIWDDEfGY0qGQ08NUOw">
      <children xmi:type="notation:DecorationNode" xmi:id="_22O1MWDDEfGY0qGQ08NUOw" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_22O1MmDDEfGY0qGQ08NUOw" type="7001">
        <children xmi:type="notation:Node" xmi:id="_22O1M2DDEfGY0qGQ08NUOw" type="3007" element="_22OOImDDEfGY0qGQ08NUOw">
          <children xmi:type="notation:DecorationNode" xmi:id="_22O1NGDDEfGY0qGQ08NUOw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_22O1NWDDEfGY0qGQ08NUOw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_22O1NmDDEfGY0qGQ08NUOw" type="3005" element="_22OOJ2DDEfGY0qGQ08NUOw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_22O1N2DDEfGY0qGQ08NUOw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_22O1OGDDEfGY0qGQ08NUOw" x="357" y="53" width="176" height="88"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_22O1OWDDEfGY0qGQ08NUOw" type="3002" element="_22OOI2DDEfGY0qGQ08NUOw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_22O1OmDDEfGY0qGQ08NUOw" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_22O1O2DDEfGY0qGQ08NUOw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_22O1PGDDEfGY0qGQ08NUOw" x="60" y="82"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_22O1PWDDEfGY0qGQ08NUOw" type="3003" element="_22OONGDDEfGY0qGQ08NUOw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_22O1PmDDEfGY0qGQ08NUOw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_22O1P2DDEfGY0qGQ08NUOw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_22O1QGDDEfGY0qGQ08NUOw" x="693" y="82"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_22O1RGDDEfGY0qGQ08NUOw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_22O1RWDDEfGY0qGQ08NUOw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_22O1RmDDEfGY0qGQ08NUOw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_22O1R2DDEfGY0qGQ08NUOw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_22O1SGDDEfGY0qGQ08NUOw"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_22O1SWDDEfGY0qGQ08NUOw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_22O1SmDDEfGY0qGQ08NUOw" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_22O1S2DDEfGY0qGQ08NUOw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_22O1TGDDEfGY0qGQ08NUOw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_22O1TWDDEfGY0qGQ08NUOw" width="1320" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_22O1TmDDEfGY0qGQ08NUOw"/>
    <edges xmi:type="notation:Connector" xmi:id="_22O1VGDDEfGY0qGQ08NUOw" type="4001" element="_22OOTGDDEfGY0qGQ08NUOw" source="_22O1NmDDEfGY0qGQ08NUOw" target="_22O1PWDDEfGY0qGQ08NUOw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_22O1VWDDEfGY0qGQ08NUOw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_22O1VmDDEfGY0qGQ08NUOw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_22O1V2DDEfGY0qGQ08NUOw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_22O1WGDDEfGY0qGQ08NUOw" points="[0, 13, -175, -2]$[160, 13, -15, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_22O1WWDDEfGY0qGQ08NUOw" id="(1.0,0.32954545454545453)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VNORQGY0EfG2XcJ39Idavg" type="4001" element="_VNNqMGY0EfG2XcJ39Idavg" source="_22O1OWDDEfGY0qGQ08NUOw" target="_22O1NmDDEfGY0qGQ08NUOw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VNORQ2Y0EfG2XcJ39Idavg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VNO4UGY0EfG2XcJ39Idavg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VNORQWY0EfG2XcJ39Idavg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VNORQmY0EfG2XcJ39Idavg" points="[-1, -13, -280, -17]$[267, 6, -12, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_VNQGcGY0EfG2XcJ39Idavg" id="(1.0,0.9333333333333333)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_VNQGcWY0EfG2XcJ39Idavg" id="(0.06818181818181818,0.6931818181818182)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
